<?php

use Illuminate\Database\Seeder;

class BuilderPagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('builder_pages')->delete();
        
        \DB::table('builder_pages')->insert(array (
            0 => 
            array (
                'id' => 1,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 1,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-16 17:26:52',
                'updated_at' => '2017-10-16 17:31:53',
                'deleted_at' => '2017-10-16 17:31:53',
            ),
            1 => 
            array (
                'id' => 2,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 3,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-16 17:26:52',
                'updated_at' => '2017-10-16 17:31:53',
                'deleted_at' => '2017-10-16 17:31:53',
            ),
            2 => 
            array (
                'id' => 3,
                'custom_module_id' => 4,
                'position' => 'T',
                'order' => 2,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-16 17:26:52',
                'updated_at' => '2017-10-23 18:03:30',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'custom_module_id' => 5,
                'position' => 'T',
                'order' => 4,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-16 17:26:52',
                'updated_at' => '2017-10-23 18:03:30',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'custom_module_id' => 6,
                'position' => 'T',
                'order' => 1,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-16 17:30:16',
                'updated_at' => '2017-10-23 18:03:30',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'custom_module_id' => 7,
                'position' => 'T',
                'order' => 3,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-16 17:30:16',
                'updated_at' => '2017-10-23 18:03:30',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 1,
                'buildable_id' => 17,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-16 18:23:29',
                'updated_at' => '2017-10-16 18:23:29',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 10,
                'custom_module_id' => 8,
                'position' => 'T',
                'order' => 3,
                'buildable_id' => 17,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-16 18:23:29',
                'updated_at' => '2017-10-31 18:00:32',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 11,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 4,
                'buildable_id' => 17,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-16 18:23:29',
                'updated_at' => '2017-10-17 19:24:50',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 12,
                'custom_module_id' => 11,
                'position' => 'T',
                'order' => 2,
                'buildable_id' => 17,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-17 19:24:50',
                'updated_at' => '2017-10-17 19:24:50',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 13,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 5,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-23 18:03:30',
                'updated_at' => '2017-10-23 18:03:30',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 14,
                'custom_module_id' => 12,
                'position' => 'T',
                'order' => 6,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-23 18:03:30',
                'updated_at' => '2017-10-23 18:03:30',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 15,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 8,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-23 18:03:30',
                'updated_at' => '2017-10-25 19:30:30',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 16,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 9,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-25 16:19:40',
                'updated_at' => '2017-10-25 19:30:30',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 17,
                'custom_module_id' => 13,
                'position' => 'T',
                'order' => 10,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-25 16:19:40',
                'updated_at' => '2017-10-25 19:30:30',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 18,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 13,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-25 16:19:40',
                'updated_at' => '2017-10-29 17:46:24',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 19,
                'custom_module_id' => 14,
                'position' => 'T',
                'order' => 11,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-25 19:29:45',
                'updated_at' => '2017-10-27 14:15:27',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 20,
                'custom_module_id' => 15,
                'position' => 'T',
                'order' => 7,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-27 14:15:26',
                'updated_at' => '2017-10-27 14:15:26',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 21,
                'custom_module_id' => 16,
                'position' => 'T',
                'order' => 12,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-29 17:46:23',
                'updated_at' => '2017-10-29 17:46:23',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 22,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 14,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-29 20:01:50',
                'updated_at' => '2017-10-29 20:01:50',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 23,
                'custom_module_id' => 17,
                'position' => 'T',
                'order' => 15,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-29 20:01:50',
                'updated_at' => '2017-10-29 20:01:50',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 24,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 16,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-29 20:01:50',
                'updated_at' => '2017-10-29 20:01:50',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 25,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 1,
                'buildable_id' => 3,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-31 17:29:09',
                'updated_at' => '2018-01-05 08:11:51',
                'deleted_at' => '2018-01-05 08:11:51',
            ),
            23 => 
            array (
                'id' => 26,
                'custom_module_id' => 18,
                'position' => 'T',
                'order' => 2,
                'buildable_id' => 3,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-31 17:29:09',
                'updated_at' => '2017-10-31 17:29:09',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 27,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 3,
                'buildable_id' => 3,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-31 17:29:10',
                'updated_at' => '2018-01-05 08:02:15',
                'deleted_at' => '2018-01-05 08:02:15',
            ),
            25 => 
            array (
                'id' => 28,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 1,
                'buildable_id' => 5,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-31 20:07:01',
                'updated_at' => '2017-10-31 20:07:01',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 29,
                'custom_module_id' => 19,
                'position' => 'T',
                'order' => 2,
                'buildable_id' => 5,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-31 20:07:01',
                'updated_at' => '2017-10-31 20:07:01',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 30,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 3,
                'buildable_id' => 5,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-31 20:07:01',
                'updated_at' => '2017-10-31 20:07:01',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 31,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 4,
                'buildable_id' => 5,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-31 20:07:01',
                'updated_at' => '2017-10-31 20:07:01',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 32,
                'custom_module_id' => 20,
                'position' => 'T',
                'order' => 5,
                'buildable_id' => 5,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-31 20:07:02',
                'updated_at' => '2017-10-31 20:07:02',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 33,
                'custom_module_id' => 16,
                'position' => 'T',
                'order' => 6,
                'buildable_id' => 5,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-31 20:07:02',
                'updated_at' => '2017-10-31 20:07:02',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 34,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 7,
                'buildable_id' => 5,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-10-31 20:07:02',
                'updated_at' => '2017-10-31 20:07:02',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 35,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 1,
                'buildable_id' => 6,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-11-03 05:10:52',
                'updated_at' => '2017-11-03 05:10:52',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 36,
                'custom_module_id' => 21,
                'position' => 'T',
                'order' => 2,
                'buildable_id' => 6,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-11-03 05:10:52',
                'updated_at' => '2017-11-03 05:10:52',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 37,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 3,
                'buildable_id' => 6,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-11-03 05:10:52',
                'updated_at' => '2017-11-03 05:10:52',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 38,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 4,
                'buildable_id' => 6,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-11-03 05:10:52',
                'updated_at' => '2017-11-03 05:10:52',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 39,
                'custom_module_id' => 20,
                'position' => 'T',
                'order' => 5,
                'buildable_id' => 6,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-11-03 05:10:52',
                'updated_at' => '2017-11-03 05:10:52',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 40,
                'custom_module_id' => 16,
                'position' => 'T',
                'order' => 6,
                'buildable_id' => 6,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-11-03 05:10:52',
                'updated_at' => '2017-11-03 05:10:52',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 41,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 7,
                'buildable_id' => 6,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-11-03 05:10:52',
                'updated_at' => '2017-11-03 05:10:52',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 42,
                'custom_module_id' => 22,
                'position' => 'T',
                'order' => 1,
                'buildable_id' => 7,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-11-05 19:51:38',
                'updated_at' => '2017-11-05 19:51:38',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 52,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 1,
                'buildable_id' => 13,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-12-01 18:14:30',
                'updated_at' => '2017-12-01 18:14:30',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 53,
                'custom_module_id' => 27,
                'position' => 'T',
                'order' => 2,
                'buildable_id' => 13,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-12-01 18:14:30',
                'updated_at' => '2017-12-01 18:14:30',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 54,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 3,
                'buildable_id' => 13,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-12-01 18:14:30',
                'updated_at' => '2017-12-01 18:14:30',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 55,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 1,
                'buildable_id' => 11,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-12-08 18:23:40',
                'updated_at' => '2017-12-08 18:23:40',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 56,
                'custom_module_id' => 25,
                'position' => 'T',
                'order' => 2,
                'buildable_id' => 11,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-12-08 18:23:41',
                'updated_at' => '2017-12-08 18:23:41',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 57,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 3,
                'buildable_id' => 11,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-12-08 18:23:41',
                'updated_at' => '2017-12-08 18:23:41',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 58,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 1,
                'buildable_id' => 12,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-12-09 17:26:30',
                'updated_at' => '2017-12-09 17:26:30',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 59,
                'custom_module_id' => 26,
                'position' => 'T',
                'order' => 2,
                'buildable_id' => 12,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-12-09 17:26:30',
                'updated_at' => '2017-12-09 17:26:30',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 60,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 3,
                'buildable_id' => 12,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-12-09 17:26:30',
                'updated_at' => '2017-12-09 17:26:30',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 61,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 1,
                'buildable_id' => 15,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-12-09 17:59:15',
                'updated_at' => '2017-12-09 17:59:15',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 62,
                'custom_module_id' => 28,
                'position' => 'T',
                'order' => 2,
                'buildable_id' => 15,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-12-09 17:59:15',
                'updated_at' => '2017-12-09 17:59:15',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 63,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 3,
                'buildable_id' => 15,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2017-12-09 17:59:15',
                'updated_at' => '2017-12-09 17:59:15',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 64,
                'custom_module_id' => 2,
                'position' => 'T',
                'order' => 3,
                'buildable_id' => 3,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-01-05 08:11:52',
                'updated_at' => '2018-01-05 08:11:52',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 65,
                'custom_module_id' => 1,
                'position' => 'T',
                'order' => 1,
                'buildable_id' => 3,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-01-05 08:12:45',
                'updated_at' => '2018-01-05 08:12:45',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 66,
                'custom_module_id' => 1,
                'position' => NULL,
                'order' => 1,
                'buildable_id' => 1,
                'buildable_type' => 'course',
                'optional_id' => NULL,
                'created_at' => '2018-01-05 08:23:45',
                'updated_at' => '2018-01-05 08:23:45',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 67,
                'custom_module_id' => 34,
                'position' => NULL,
                'order' => 2,
                'buildable_id' => 1,
                'buildable_type' => 'course',
                'optional_id' => NULL,
                'created_at' => '2018-01-05 08:23:45',
                'updated_at' => '2018-05-20 15:42:09',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 68,
                'custom_module_id' => 2,
                'position' => NULL,
                'order' => 3,
                'buildable_id' => 1,
                'buildable_type' => 'course',
                'optional_id' => NULL,
                'created_at' => '2018-01-05 08:23:45',
                'updated_at' => '2018-01-05 08:23:45',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 77,
                'custom_module_id' => 1,
                'position' => NULL,
                'order' => 1,
                'buildable_id' => 19,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-04-18 17:28:08',
                'updated_at' => '2018-04-18 17:28:08',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 78,
                'custom_module_id' => 31,
                'position' => NULL,
                'order' => 2,
                'buildable_id' => 19,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-04-18 17:28:08',
                'updated_at' => '2018-04-18 17:28:08',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 79,
                'custom_module_id' => 2,
                'position' => NULL,
                'order' => 3,
                'buildable_id' => 19,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-04-18 17:28:08',
                'updated_at' => '2018-04-18 17:28:08',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 80,
                'custom_module_id' => 1,
                'position' => NULL,
                'order' => 1,
                'buildable_id' => 25,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-04-18 17:43:34',
                'updated_at' => '2018-04-18 17:43:34',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 81,
                'custom_module_id' => 32,
                'position' => NULL,
                'order' => 2,
                'buildable_id' => 25,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-04-18 17:43:34',
                'updated_at' => '2018-04-18 17:43:34',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 82,
                'custom_module_id' => 2,
                'position' => NULL,
                'order' => 3,
                'buildable_id' => 25,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-04-18 17:43:34',
                'updated_at' => '2018-04-18 17:43:34',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 83,
                'custom_module_id' => 3,
                'position' => NULL,
                'order' => 17,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-05-18 05:30:32',
                'updated_at' => '2018-05-23 19:57:20',
                'deleted_at' => '2018-05-23 19:57:20',
            ),
            64 => 
            array (
                'id' => 84,
                'custom_module_id' => 33,
                'position' => NULL,
                'order' => 18,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-05-18 05:30:33',
                'updated_at' => '2018-05-18 05:30:33',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 85,
                'custom_module_id' => 2,
                'position' => NULL,
                'order' => 19,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-05-18 05:30:33',
                'updated_at' => '2018-05-23 19:57:21',
                'deleted_at' => '2018-05-23 19:57:21',
            ),
            66 => 
            array (
                'id' => 86,
                'custom_module_id' => 1,
                'position' => NULL,
                'order' => 1,
                'buildable_id' => 1,
                'buildable_type' => 'person',
                'optional_id' => NULL,
                'created_at' => '2018-05-21 15:51:13',
                'updated_at' => '2018-05-21 15:51:13',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 87,
                'custom_module_id' => 23,
                'position' => NULL,
                'order' => 2,
                'buildable_id' => 1,
                'buildable_type' => 'person',
                'optional_id' => NULL,
                'created_at' => '2018-05-21 15:51:13',
                'updated_at' => '2018-05-21 15:51:13',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 88,
                'custom_module_id' => 2,
                'position' => NULL,
                'order' => 3,
                'buildable_id' => 1,
                'buildable_type' => 'person',
                'optional_id' => NULL,
                'created_at' => '2018-05-21 15:51:13',
                'updated_at' => '2018-05-21 15:51:13',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 89,
                'custom_module_id' => 3,
                'position' => NULL,
                'order' => 17,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-05-23 20:02:11',
                'updated_at' => '2018-05-23 20:02:11',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 90,
                'custom_module_id' => 2,
                'position' => NULL,
                'order' => 19,
                'buildable_id' => 1,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-05-23 20:02:11',
                'updated_at' => '2018-05-23 20:02:11',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 91,
                'custom_module_id' => 1,
                'position' => NULL,
                'order' => 1,
                'buildable_id' => 16,
                'buildable_type' => 'page',
                'optional_id' => 6,
                'created_at' => '2018-05-26 15:09:26',
                'updated_at' => '2018-05-26 15:09:26',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 92,
                'custom_module_id' => 35,
                'position' => NULL,
                'order' => 2,
                'buildable_id' => 16,
                'buildable_type' => 'page',
                'optional_id' => 6,
                'created_at' => '2018-05-26 15:09:26',
                'updated_at' => '2018-05-26 15:09:26',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 93,
                'custom_module_id' => 2,
                'position' => NULL,
                'order' => 3,
                'buildable_id' => 16,
                'buildable_type' => 'page',
                'optional_id' => 6,
                'created_at' => '2018-05-26 15:09:26',
                'updated_at' => '2018-05-26 15:09:26',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 94,
                'custom_module_id' => 1,
                'position' => NULL,
                'order' => 1,
                'buildable_id' => 1,
                'buildable_type' => 'lab',
                'optional_id' => NULL,
                'created_at' => '2018-05-26 16:39:10',
                'updated_at' => '2018-05-26 16:39:10',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 95,
                'custom_module_id' => 36,
                'position' => NULL,
                'order' => 2,
                'buildable_id' => 1,
                'buildable_type' => 'lab',
                'optional_id' => NULL,
                'created_at' => '2018-05-26 16:39:10',
                'updated_at' => '2018-05-26 16:39:10',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 96,
                'custom_module_id' => 2,
                'position' => NULL,
                'order' => 3,
                'buildable_id' => 1,
                'buildable_type' => 'lab',
                'optional_id' => NULL,
                'created_at' => '2018-05-26 16:39:10',
                'updated_at' => '2018-05-26 16:39:10',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 97,
                'custom_module_id' => 1,
                'position' => NULL,
                'order' => 1,
                'buildable_id' => 10,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-05-27 15:54:43',
                'updated_at' => '2018-05-27 15:54:43',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 98,
                'custom_module_id' => 37,
                'position' => NULL,
                'order' => 2,
                'buildable_id' => 10,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-05-27 15:54:43',
                'updated_at' => '2018-05-27 15:54:43',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 99,
                'custom_module_id' => 2,
                'position' => NULL,
                'order' => 3,
                'buildable_id' => 10,
                'buildable_type' => 'page',
                'optional_id' => NULL,
                'created_at' => '2018-05-27 15:54:43',
                'updated_at' => '2018-05-27 15:54:43',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}