<?php

use Illuminate\Database\Seeder;

class SiteMenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('site_menus')->delete();
        
        \DB::table('site_menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                '_lft' => 1,
                '_rgt' => 4,
                'parent_id' => NULL,
                'order' => 1,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 1,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 17:49:52',
                'updated_at' => '2017-11-14 17:56:25',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                '_lft' => 5,
                '_rgt' => 26,
                'parent_id' => NULL,
                'order' => 2,
                'prefix' => NULL,
                'is_link' => 0,
                'menuable_id' => NULL,
                'menuable_type' => NULL,
                'dynamic' => NULL,
                'created_at' => '2017-10-14 17:56:06',
                'updated_at' => '2018-03-26 19:44:08',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                '_lft' => 6,
                '_rgt' => 7,
                'parent_id' => 2,
                'order' => 1,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 3,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 17:59:47',
                'updated_at' => '2018-03-26 19:44:24',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                '_lft' => 8,
                '_rgt' => 9,
                'parent_id' => 2,
                'order' => 2,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 4,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 17:59:57',
                'updated_at' => '2018-03-26 19:44:24',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                '_lft' => 10,
                '_rgt' => 13,
                'parent_id' => 2,
                'order' => 11,
                'prefix' => NULL,
                'is_link' => 0,
                'menuable_id' => NULL,
                'menuable_type' => NULL,
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:01:05',
                'updated_at' => '2018-03-26 19:34:57',
                'deleted_at' => '2018-03-26 19:34:57',
            ),
            5 => 
            array (
                'id' => 6,
                '_lft' => 11,
                '_rgt' => 12,
                'parent_id' => 5,
                'order' => 2,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 6,
                'menuable_type' => 'faculty',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:01:56',
                'updated_at' => '2017-11-12 19:18:06',
                'deleted_at' => '2017-10-14 18:02:16',
            ),
            6 => 
            array (
                'id' => 7,
                '_lft' => 14,
                '_rgt' => 15,
                'parent_id' => 2,
                'order' => 4,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 5,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:07:52',
                'updated_at' => '2018-03-26 19:44:24',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                '_lft' => 16,
                '_rgt' => 17,
                'parent_id' => 2,
                'order' => 5,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 6,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:07:59',
                'updated_at' => '2018-03-26 19:44:24',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                '_lft' => 18,
                '_rgt' => 19,
                'parent_id' => 2,
                'order' => 6,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 7,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:08:11',
                'updated_at' => '2018-03-26 19:44:24',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                '_lft' => 27,
                '_rgt' => 28,
                'parent_id' => NULL,
                'order' => 8,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 8,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:08:14',
                'updated_at' => '2018-03-26 19:44:08',
                'deleted_at' => '2017-10-14 18:08:51',
            ),
            10 => 
            array (
                'id' => 11,
                '_lft' => 20,
                '_rgt' => 21,
                'parent_id' => 2,
                'order' => 8,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 10,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:08:21',
                'updated_at' => '2018-03-26 19:44:25',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                '_lft' => 22,
                '_rgt' => 23,
                'parent_id' => 2,
                'order' => 7,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 8,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:09:00',
                'updated_at' => '2018-03-26 19:44:24',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                '_lft' => 30,
                '_rgt' => 31,
                'parent_id' => 14,
                'order' => 1,
                'prefix' => NULL,
                'is_link' => 0,
                'menuable_id' => NULL,
                'menuable_type' => NULL,
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:11:23',
                'updated_at' => '2018-03-26 19:44:08',
                'deleted_at' => '2017-11-12 19:48:19',
            ),
            13 => 
            array (
                'id' => 14,
                '_lft' => 29,
                '_rgt' => 48,
                'parent_id' => NULL,
                'order' => 3,
                'prefix' => NULL,
                'is_link' => 0,
                'menuable_id' => NULL,
                'menuable_type' => NULL,
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:12:30',
                'updated_at' => '2018-03-26 19:44:09',
                'deleted_at' => '2017-11-12 19:50:47',
            ),
            14 => 
            array (
                'id' => 15,
                '_lft' => 32,
                '_rgt' => 47,
                'parent_id' => 14,
                'order' => 2,
                'prefix' => NULL,
                'is_link' => 0,
                'menuable_id' => NULL,
                'menuable_type' => NULL,
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:13:31',
                'updated_at' => '2018-03-26 19:44:09',
                'deleted_at' => '2017-11-12 19:50:08',
            ),
            15 => 
            array (
                'id' => 16,
                '_lft' => 80,
                '_rgt' => 81,
                'parent_id' => 44,
                'order' => 1,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 11,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:21:35',
                'updated_at' => '2018-03-26 19:44:11',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                '_lft' => 82,
                '_rgt' => 83,
                'parent_id' => 44,
                'order' => 2,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 12,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:21:45',
                'updated_at' => '2018-03-26 19:44:11',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                '_lft' => 84,
                '_rgt' => 85,
                'parent_id' => 44,
                'order' => 3,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 13,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:21:58',
                'updated_at' => '2018-03-26 19:44:11',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                '_lft' => 86,
                '_rgt' => 87,
                'parent_id' => 44,
                'order' => 4,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 14,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:22:03',
                'updated_at' => '2018-03-26 19:44:11',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                '_lft' => 88,
                '_rgt' => 89,
                'parent_id' => 44,
                'order' => 5,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 15,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:22:10',
                'updated_at' => '2018-03-26 19:44:11',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                '_lft' => 90,
                '_rgt' => 91,
                'parent_id' => 44,
                'order' => 6,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 16,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:22:22',
                'updated_at' => '2018-03-26 19:44:11',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                '_lft' => 33,
                '_rgt' => 34,
                'parent_id' => 15,
                'order' => 1,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 11,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:22:44',
                'updated_at' => '2018-03-26 19:44:08',
                'deleted_at' => '2017-11-12 19:41:50',
            ),
            22 => 
            array (
                'id' => 23,
                '_lft' => 35,
                '_rgt' => 36,
                'parent_id' => 15,
                'order' => 2,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 12,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:22:47',
                'updated_at' => '2018-03-26 19:44:09',
                'deleted_at' => '2017-11-12 19:49:43',
            ),
            23 => 
            array (
                'id' => 24,
                '_lft' => 37,
                '_rgt' => 38,
                'parent_id' => 15,
                'order' => 3,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 13,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:22:53',
                'updated_at' => '2018-03-26 19:44:09',
                'deleted_at' => '2017-11-12 19:49:34',
            ),
            24 => 
            array (
                'id' => 25,
                '_lft' => 39,
                '_rgt' => 40,
                'parent_id' => 15,
                'order' => 4,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 14,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:22:58',
                'updated_at' => '2018-03-26 19:44:09',
                'deleted_at' => '2017-11-12 19:49:08',
            ),
            25 => 
            array (
                'id' => 26,
                '_lft' => 41,
                '_rgt' => 42,
                'parent_id' => 15,
                'order' => 5,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 15,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:23:07',
                'updated_at' => '2018-03-26 19:44:09',
                'deleted_at' => '2017-11-12 19:48:58',
            ),
            26 => 
            array (
                'id' => 27,
                '_lft' => 43,
                '_rgt' => 44,
                'parent_id' => 15,
                'order' => 6,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 16,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:23:17',
                'updated_at' => '2018-03-26 19:44:09',
                'deleted_at' => '2017-11-12 19:48:47',
            ),
            27 => 
            array (
                'id' => 28,
                '_lft' => 45,
                '_rgt' => 46,
                'parent_id' => 15,
                'order' => 7,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 16,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:23:22',
                'updated_at' => '2018-03-26 19:44:09',
                'deleted_at' => '2017-10-14 18:23:40',
            ),
            28 => 
            array (
                'id' => 29,
                '_lft' => 49,
                '_rgt' => 50,
                'parent_id' => NULL,
                'order' => 6,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 17,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:26:14',
                'updated_at' => '2018-03-26 19:44:09',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                '_lft' => 51,
                '_rgt' => 52,
                'parent_id' => NULL,
                'order' => 7,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 18,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:26:23',
                'updated_at' => '2018-03-26 19:44:09',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                '_lft' => 53,
                '_rgt' => 54,
                'parent_id' => NULL,
                'order' => 6,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 18,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:26:28',
                'updated_at' => '2018-03-26 19:44:09',
                'deleted_at' => '2017-10-14 18:26:39',
            ),
            31 => 
            array (
                'id' => 32,
                '_lft' => 55,
                '_rgt' => 56,
                'parent_id' => NULL,
                'order' => 8,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 19,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:26:55',
                'updated_at' => '2018-03-26 19:44:09',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                '_lft' => 57,
                '_rgt' => 66,
                'parent_id' => NULL,
                'order' => 4,
                'prefix' => NULL,
                'is_link' => 0,
                'menuable_id' => NULL,
                'menuable_type' => NULL,
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:27:33',
                'updated_at' => '2018-03-26 19:44:10',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                '_lft' => 67,
                '_rgt' => 74,
                'parent_id' => NULL,
                'order' => 5,
                'prefix' => NULL,
                'is_link' => 0,
                'menuable_id' => NULL,
                'menuable_type' => NULL,
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:28:04',
                'updated_at' => '2018-03-26 19:44:10',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                '_lft' => 62,
                '_rgt' => 63,
                'parent_id' => 33,
                'order' => 1,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 20,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:52:22',
                'updated_at' => '2018-03-26 19:44:10',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                '_lft' => 64,
                '_rgt' => 65,
                'parent_id' => 33,
                'order' => 2,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 21,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:52:27',
                'updated_at' => '2018-03-26 19:44:10',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                '_lft' => 58,
                '_rgt' => 59,
                'parent_id' => 33,
                'order' => 3,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 22,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:52:40',
                'updated_at' => '2018-03-26 19:44:10',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                '_lft' => 60,
                '_rgt' => 61,
                'parent_id' => 33,
                'order' => 4,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 23,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:52:58',
                'updated_at' => '2018-03-26 19:44:10',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                '_lft' => 70,
                '_rgt' => 71,
                'parent_id' => 34,
                'order' => 1,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 24,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:53:14',
                'updated_at' => '2018-03-26 19:44:10',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                '_lft' => 72,
                '_rgt' => 73,
                'parent_id' => 34,
                'order' => 2,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 25,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:53:18',
                'updated_at' => '2018-03-26 19:44:10',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                '_lft' => 68,
                '_rgt' => 69,
                'parent_id' => 34,
                'order' => 3,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 26,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-14 18:53:48',
                'updated_at' => '2018-03-26 19:44:10',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                '_lft' => 75,
                '_rgt' => 76,
                'parent_id' => NULL,
                'order' => 10,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 2,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-15 12:20:57',
                'updated_at' => '2018-03-26 19:44:10',
                'deleted_at' => '2017-10-15 12:21:34',
            ),
            42 => 
            array (
                'id' => 43,
                '_lft' => 77,
                '_rgt' => 78,
                'parent_id' => NULL,
                'order' => 10,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 2,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2017-10-15 12:21:00',
                'updated_at' => '2018-03-26 19:44:10',
                'deleted_at' => '2017-10-15 12:21:24',
            ),
            43 =>
            array (
                'id' => 44,
                '_lft' => 79,
                '_rgt' => 92,
                'parent_id' => NULL,
                'order' => 3,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 14,
                'menuable_type' => 'tables',
                'dynamic' => 'faculty',
                'created_at' => '2017-11-12 19:38:23',
                'updated_at' => '2018-03-26 19:44:11',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                '_lft' => 2,
                '_rgt' => 3,
                'parent_id' => 1,
                'order' => 2,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 14,
                'menuable_type' => 'tables',
                'dynamic' => 'faculty',
                'created_at' => '2017-11-12 19:45:06',
                'updated_at' => '2017-11-12 19:46:05',
                'deleted_at' => '2017-11-12 19:46:05',
            ),
            45 => 
            array (
                'id' => 46,
                '_lft' => 24,
                '_rgt' => 25,
                'parent_id' => 2,
                'order' => 3,
                'prefix' => NULL,
                'is_link' => 1,
                'menuable_id' => 29,
                'menuable_type' => 'page',
                'dynamic' => NULL,
                'created_at' => '2018-03-26 19:44:08',
                'updated_at' => '2018-03-26 19:44:24',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}