<li data-index="rs-{{ $i }}" data-transition="slidingoverlayhorizontal" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="{{ $imageThumb }}" data-rotate="0" data-saveperformance="off" data-title="Web Show" data-description="">
    <img src="{{ $image }}"  alt=""  data-bgposition="center {{ $bgposition }}" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-bgparallax="6" data-no-retina>
    <!-- LAYER NR. 1 -->
    <div class="{{ $layers['1']['class'] }}"
         id="rs-{{ $i }}-layer-1"
         data-x="['{{ $layers['1']['x'] }}']"
         data-hoffset="['{{ $layers['1']['hoffset'] }}']"
         data-y="['middle']"
         data-voffset="['{{ $layers['1']['voffset'] }}']"
         data-fontsize="['{{ $layers['1']['fontsize'] }}']"
         data-lineheight="['{{ $layers['1']['lineheight'] }}']"
         data-width="none"
         data-height="none"
         data-whitespace="nowrap"
         data-transform_idle="o:1;s:500"
         data-transform_in="y:100;scaleX:1;scaleY:1;opacity:0;"
         data-transform_out="x:left(R);s:1000;e:Power3.easeIn;s:1000;e:Power3.easeIn;"
         data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
         data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;"
         data-start="1000"
         data-splitin="none"
         data-splitout="none"
         data-responsive_offset="on"
         style="{{ $layers['1']['style'] }}">{{ $layers['1']['data'] }}
    </div>
    <!-- LAYER NR. 2 -->
    <div class="{{ $layers['2']['class'] }}"
         id="rs-{{ $i }}-layer-2"
         data-x="['{{ $layers['2']['x'] }}']"
         data-hoffset="['{{ $layers['2']['hoffset'] }}']"
         data-y="['middle']"
         data-voffset="['{{ $layers['2']['voffset'] }}']"
         data-fontsize="['{{ $layers['2']['fontsize'] }}']"
         data-lineheight="['{{ $layers['2']['lineheight'] }}']"
         data-width="none"
         data-height="none"
         data-whitespace="nowrap"
         data-transform_idle="o:1;s:500"
         data-transform_in="y:100;scaleX:1;scaleY:1;opacity:0;"
         data-transform_out="x:left(R);s:1000;e:Power3.easeIn;s:1000;e:Power3.easeIn;"
         data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
         data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;"
         data-start="1000"
         data-splitin="none"
         data-splitout="none"
         data-responsive_offset="on"
         style="{{ $layers['2']['style'] }}">{{ $layers['2']['data'] }}
    </div>
    <!-- LAYER NR. 3 -->
    <div class="{{ $layers['3']['class'] }}"
         id="rs-{{ $i }}-layer-3"
         data-x="['{{ $layers['3']['x'] }}']"
         data-hoffset="['{{ $layers['3']['hoffset'] }}']"
         data-y="['middle']"
         data-voffset="['{{ $layers['3']['voffset'] }}']"
         data-fontsize="['{{ $layers['3']['fontsize'] }}']"
         data-lineheight="['{{ $layers['3']['lineheight'] }}']"
         data-width="none"
         data-height="none"
         data-whitespace="nowrap"
         data-transform_idle="o:1;s:500"
         data-transform_in="y:100;scaleX:1;scaleY:1;opacity:0;"
         data-transform_out="x:left(R);s:1000;e:Power3.easeIn;s:1000;e:Power3.easeIn;"
         data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
         data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;"
         data-start="1400"
         data-splitin="none"
         data-splitout="none"
         data-responsive_offset="on"
         style="{{ $layers['3']['style'] }}">{{ $layers['3']['data'] }}
    </div>
    <!-- LAYER NR. 4 -->
    <div class="{{ $layers['4']['class'] }}"
         id="rs-{{ $i }}-layer-4"
         data-x="['{{ $layers['4']['x'] }}']"
         data-hoffset="['{{ $layers['4']['hoffset'] }}']"
         data-y="['middle']"
         data-voffset="['{{ $layers['4']['voffset'] }}']"
         data-width="none"
         data-height="none"
         data-whitespace="nowrap"
         data-transform_idle="o:1;"
         data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power4.easeInOut;"
         data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
         data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
         data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;"
         data-start="1400"
         data-splitin="none"
         data-splitout="none"
         data-responsive_offset="on"
         style="{{ $layers['4']['style'] }}"><a class="{{ $layers['4']['link_class'] }}" href="#">{{ $layers['4']['data'] }}</a>
    </div>
</li>